### ISSUE TITLE
[ЗАДАЧА] Интерфейс

### ISSUE THREAD

**Issue by BusterDaemon** [rembov/bitva-za-stakan-vody#13]
Отсутствует нормальная логика интерфейса, необходимо реализовать нормальную.

**Comment by MrBlazer335** [comment]
О каком интерфейсе идет речь?

**Comment by rembov** [comment]
Надо,как минимум продумать логику возвращения в главное меню.А дальше можешь чё нибудь свое придумать.

**Comment by BusterDaemon** [comment]
> О каком интерфейсе идет речь?

Текстовом. У которого пока нету нормальной логики перехода по пунктам меню.
