### ISSUE TITLE
[ВОПРОС]: база данных

### ISSUE THREAD

**Issue by BusterDaemon** [rembov/bitva-za-stakan-vody#5]
Непонятно что нужно для базы данных, если планируется система подсчёта очков то нужно, что-то что их начисляет. Даже если и будет реализована система очков то помимо ника и самих очков, что ещё нужно будет записывать в БД.
Также нужен план развития проекта, что должно быть реализовано.

**Comment by rembov** [comment]
БД будет с двумя столбиками.1 ник 2 стата.Значит еще нужно добавить сортировку по очкам при выводе бд в консоль.

**Comment by rembov** [comment]
Можно mySQL заюзать.Она в роде встроена уже (import Java.sql).

**Comment by rembov** [comment]
Теперь план.
1. Нужно реализовать 2 игры.
  а)типа пинг-понг(линия мячиком или кокосом сбивает другие кокосы )
  б)типа кости(через рандом реализация(зачатки уже есть,нужно как-то развить)
2.Подключить бд со статой и никами
на этом пока все,можете накидывать своих идей(приветствуется)

**Comment by BusterDaemon** [comment]
> Можно mySQL заюзать.Она в роде встроена уже (import Java.sql).

Для MySQL сервак нужен, не думаю, что у обычного игрока он есть. Предлагаю использовать SQLite, если возможно, ведь она есть почти везде

**Comment by rembov** [comment]
Изучи тогда,просто я с бд только на змее воркал.

**Comment by BusterDaemon** [comment]
>  а)типа пинг-понг(линия мячиком или кокосом сбивает другие кокосы )

Хз, как это реализовать с голой стандартной библиотекой из принтов. Предлагаю сделать что-то попроще, так я сейчас делаю "отгадайку", где типа нужно координаты с водой отгадать.

**Comment by BusterDaemon** [comment]
>  б)типа кости(через рандом реализация(зачатки уже есть,нужно как-то развить)

Предлагаю сделать только ставку какой номер победит, чем ближе к победителю тем больше очков

**Comment by BusterDaemon** [comment]
> Изучи тогда,просто я с бд только на змее воркал.

SQLite встроена в стандартную библиотеку
https://www.tutorialspoint.com/sqlite/sqlite_java.htm

**Comment by rembov** [comment]
я о ней и говорил
